name: Lock Inactive Issues

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@c922f5b23611024bc9d94833ae147f6048ab0275
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
